In [13]:
import numpy as np

a = np.random.randn(5)

In [14]:
print(a)

[-1.27091871 -2.10167142  0.53872257  0.82925618 -0.66787181]


In [15]:
print(a.shape)
# (5,) is a funny data structure which is neither row vector nor column vector
# it is called " rank 1 array "
# when you're implementing logistic regression or neural networks that you just do not use these rank 1 arrays.

(5,)


In [16]:
assert(a.shape == (5,1))
# this error gives us clarity that np.random.randn(5) did not produce either a column vector or a row vector.

AssertionError: 

In [4]:
print(a.T)

[-0.0628794   0.10281424  1.36130978 -0.43644476  0.67801402]


In [5]:
print(np.dot(a,a.T))

2.5178759347082647


In [6]:
a = np.random.randn(5,1)
print(a)

[[-0.1482686 ]
 [ 1.76519012]
 [-0.30920555]
 [-0.23247556]
 [-0.27886375]]


In [8]:
print(a.T)

[[-0.1482686   1.76519012 -0.30920555 -0.23247556 -0.27886375]]


In [7]:
print(np.dot(a,a.T))

[[ 0.02198358 -0.26172227  0.04584548  0.03446883  0.04134674]
 [-0.26172227  3.11589617 -0.54580659 -0.41036357 -0.49224754]
 [ 0.04584548 -0.54580659  0.09560807  0.07188273  0.08622622]
 [ 0.03446883 -0.41036357  0.07188273  0.05404489  0.06482901]
 [ 0.04134674 -0.49224754  0.08622622  0.06482901  0.07776499]]


In [12]:
assert(a.shape == (5,1))

In [24]:
a = np.random.randn(3,3)
b = np.random.randn(3,1)
c = a*b
print(c,c.shape)

[[ 0.70454211  0.67001936  1.38125318]
 [ 0.19882258  0.14153677  0.14034268]
 [-0.0726872   2.15488149  1.53251813]] (3, 3)


In [23]:
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]
print(c)

IndexError: index 1 is out of bounds for axis 0 with size 1